backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Conteúdo do Site"
    files:
      - label: "Informações gerais"
        name: "geral"
        file: "content/geral.json"
        fields:
          - { label: "Título principal", name: "hero_title", widget: "string" }
          - { label: "Texto do hero", name: "hero_text", widget: "text" }
